CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Models/Posting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CommunityProject_ProjectUnity.Models
{
    public class Posting : Auditable, IValidatableObject
    {
        public Posting()
        {
            this.Applications = new HashSet<Application>();
            this.Skills = new HashSet<Skill>();
            this.Qualifications = new HashSet<Qualification>();
            this.Schools = new HashSet<School>();
            this.Applicants = new HashSet<Applicant>();
           
        }
        public int ID { get; set; }



        [Display(Name = "Posting")]
        public string Summary
        {
            get
            {
                return Position?.Name;
            }
        }

        [Display(Name = "Posting")]
        public string ClosingSummary
        {
            get
            {
                string tense = (ClosingDate < DateTime.Today) ? "Closed: " : "Closing: ";
                return tense + ClosingDate.ToShortDateString();
            }
        }

        [Display(Name = "Posting")]
        public string FullSummary
        {
            get
            {
                return Position?.Name + " - " + ClosingSummary;
            }
        }

        [Required(ErrorMessage = "Posting Name is Required")]
        [Display(Name = "Job Posting")]
        [StringLength(150, ErrorMessage = "Posting Name Must Be Shorter Than 150 Characters")]
        public string Name { get; set; }


        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }


        [Display(Name = "Closing Date")]
        [Required(ErrorMessage = "You must specify the closing date for the job posting.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime ClosingDate { get; set; }


        [Display(Name = "Job Start Date")]
        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? JobStartDate { get; set; }

        [Display(Name = "Job End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? JobEndDate { get; set; }

        [Display(Name = "Posting Status")]
        [Required(ErrorMessage = "You must provide a posting status.")]
        public string status { get; set; }

       

        [Display(Name = "Full Time Equivalent")]
        [Required(ErrorMessage = "You must specify the F.T.E for the job posting.")]
        [Range(typeof(double), "0.1", "1.2", ErrorMessage = "FTE has to be between 0.1 and 1.2")]
        public double? FTE { get; set; }

        [Display(Name = "Number of Openings")]
        [Required(ErrorMessage = "You must specify how many positions are open.")]
        [Range(1, 9999, ErrorMessage = "Invalid number of job openings.")]
        public int Openings { get; set; }

        [Required(ErrorMessage = "Salary Required")]
        [Display(Name = "Salary")]
        [Range(0.01, 999999.99, ErrorMessage = "Salary must be between $0.01 and $999999.99")]
        [DataType(DataType.Currency)]
        public decimal Salary { get; set; }

        [Required(ErrorMessage = "Salary Type Required")]
        [Display(Name = "Salary Type")]
        public string SalaryType { get; set; }


        [Required(ErrorMessage = "Posting Description Required")]
        [Display(Name = "Posting Description")]
        [StringLength(1200, ErrorMessage = "Description Must Be Shorter Than 400 Characters")]
        public string Description { get; set; }

        public int OpeningCount { get; set; }

        [Required(ErrorMessage = "Position Type is Required")]
        public string PositionType { get; set; }
        public int PositionID { get; set; }
        

        public virtual ICollection<Application> Applications { get; set; }

        public virtual Position Position { get; set; }

       

       

        public virtual ICollection<School> Schools { get; set; }

        
        public virtual ICollection<Skill> Skills { get; set; }

       

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (ClosingDate < DateTime.Today)
            {
                yield return new ValidationResult("The closing date cannot be in the past.", new[] { "ClosingDate" });
            }
            if (StartDate.GetValueOrDefault() < System.DateTime.Today)
            {
                yield return new ValidationResult("The start date for the posting cannot be before the current date.", new[] { "StartDate" });
            }
        }



       
        public virtual ICollection<Qualification> Qualifications { get; set; }

        public virtual ICollection<Applicant> Applicants { get; set; }

    }
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Controllers/PostingsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CommunityProject_ProjectUnity.DAL;
using CommunityProject_ProjectUnity.Models;
using CommunityProject_ProjectUnity.ViewModels;
using PagedList;

namespace CommunityProject_ProjectUnity.Controllers
{
    [Authorize]
    public class PostingsController : Controller
    {
        private ProjectUnityEntities db = new ProjectUnityEntities();

        // GET: Postings
        public ActionResult Index(string sortDirection, string sortField,
            string actionButton, string searchName,  string searchStatus, string SalaryType, string School, string searchFTE, string[] selectedOptions, int? page)
        {
            PopulateDropDownLists();
            ViewBag.School= new SelectList(db.Schools.OrderBy(p => p.Name), "Name", "Name");
            ViewBag.Filtering = ""; //Assume not filtering

            //Prepare a ghost Posting to help maintain the selected skills
            var posting = new Posting();
            posting.Skills = new List<Skill>();
            posting.Qualifications = new List<Qualification>();

            //LINQ - Start with the Includes
            var postings = db.Postings.AsNoTracking()
                .Include(p => p.Position)
                .Include(p=>p.Schools)
               
                .Include(p => p.Skills);
                
            if (!User.IsInRole("Admin"))
            {
                postings = postings.Where(p => p.status == "Current");
            }



            //Add as many filters as you want
            if (!String.IsNullOrEmpty(searchName))
            {
                postings = postings.Where(p => p.Name.ToUpper().Contains(searchName.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.searchName = searchName;
            }
           
            if (!String.IsNullOrEmpty(searchStatus))
            {
                postings = postings.Where(p => p.status.ToUpper().Contains(searchStatus.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.searchStatus = searchStatus;
            }


            if (!String.IsNullOrEmpty(SalaryType))
            {
                if(SalaryType=="1")
                {
                    postings = postings.Where(p => p.SalaryType=="Hourly");
                }
                if(SalaryType=="2")
                {
                    postings = postings.Where(p => p.SalaryType == "Annually");
                }
                
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.SalaryType = SalaryType;
            }

            if (!String.IsNullOrEmpty(searchFTE))
            {
                if (searchFTE == "1")
                {
                    postings = postings.Where(p => p.FTE < 0.5);
                    ViewBag.Filtering = " in";//Flag filtering
                    ViewBag.searchName = searchFTE;
                }
                else
                {
                    postings = postings.Where(p => p.FTE >= 0.5);
                    ViewBag.Filtering = " in";//Flag filtering
                    ViewBag.searchName = searchFTE;
                }
            }

            //Before we sort, see if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted so lets sort!
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = String.IsNullOrEmpty(sortDirection) ? "desc" : "";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            //Now we know which field and direction to sort by, but a Switch is hard to use for 2 criteria
            //so we will use an if() structure instead.
            if (sortField == "Number of Openings")//Sorting by Applicant Name
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    postings = postings
                        .OrderBy(p => p.Openings);
                }
                else
                {
                    postings = postings
                        .OrderByDescending(p => p.Openings);
                }
            }
            else if (sortField == "Closing Date")
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    postings = postings
                        .OrderBy(p => p.ClosingDate);
                }
                else
                {
                    postings = postings
                        .OrderByDescending(p => p.ClosingDate);
                }
            }
            else if (sortField == "Full Time Equivalent")
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    postings = postings
                        .OrderBy(p => p.FTE);
                }
                else
                {
                    postings = postings
                        .OrderByDescending(p => p.FTE);
                }
            }
            else //By default sort by Position NAME
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    postings = postings
                        .OrderBy(p => p.Position.Name);
                }
                else
                {
                    postings = postings
                        .OrderByDescending(p => p.Position.Name);
                }
            }
            ViewBag.searchStatus = new SelectList(Status, "Value", "Text", posting?.status);
            
           
            //Prepare the check boxes
            PopulateAssignedSkillData(posting);
            PopulateAssignedQualificationData(posting);

            //Set sort for next time
            ViewBag.sortField = sortField;
            ViewBag.sortDirection = sortDirection;

            int pageSize = 550;
            int pageNumber = (page ?? 1);
            if (!User.IsInRole("Admin"))
            {
                return View("Indexuser", postings.Where(p =>p.status=="Current")
                    .ToPagedList(pageNumber, pageSize));
            }
            return View(postings.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult UserView()
        {
            return View(db.Postings.ToList());
        }
        //public ActionResult Index()
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        return View("Indexuser", db.Postings.OrderBy(p => p.Name).ToPagedList(1, 25));
        //    }

        //    return View(db.Postings.OrderBy(p => p.Name).ToPagedList(1, 25));

        //}
        // GET: Postings/Details/5
        public ActionResult Details(int? id, string message)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posting posting = db.Postings.AsNoTracking()
                //.Include(p  =>p.City)
                //.Include(p => p.School)
                .Include(p => p.Skills)
                .Include(p =>p.Qualifications)
                .Include(p => p.Position)
                .Include(p =>p.Applications)
                .Where(p => p.ID == id).SingleOrDefault();
            var postype = posting.PositionType;
            if(postype=="Teaching")
            {
                ViewBag.SkillsList = posting.Qualifications.ToList();
            }
            if(postype=="Non-Teaching")
            {
                ViewBag.SkillsList = posting.Skills.ToList();
            }
            if (posting == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = message;
            ViewBag.Closed = posting.ClosingDate < DateTime.Today;
            return View(posting);
        }

        // GET: Postings/Create
        
        public ActionResult CreateStart()
        {
            PopulateDropDownLists();
            return View("CreateStart");
        }

        // GET: Postings/Create
        //public ActionResult Create()
        //{
        //    PopulateDropDownLists();
        //    //Add all (unchecked) Skills to ViewBag
        //    var posting = new Posting();
        //    posting.Skills = new List<Skill>();
        //    posting.Qualifications = new List<Qualification>();
        //    var result = (from skills in db.Skills select skills).ToList();
        //    var qResult = (from qualifications in db.Qualifications select qualifications).ToList();
        //    if (result != null)
        //    {
        //        ViewBag.mySkills = result.Select(N => new SelectListItem { Text = N.SkillName, Value = N.ID.ToString() });
        //    }
        //    if (result != null)
        //    {
        //        ViewBag.myQualifications = qResult.Select(N => new SelectListItem { Text = N.Name, Value = N.ID.ToString() });
        //    }
        //    PopulateAssignedSkillData(posting);
        //    PopulateAssignedQualificationData(posting);
        //    return View();
        //}
        public ActionResult Create(int? PositionID)
        {
            Position position = db.Positions
                .Include(p => p.Skills)
                .Where(p => p.ID == PositionID)
               
                .SingleOrDefault();
            if (position == null)
            {

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Postings/CSVUpload.cshtml
@{
    ViewBag.Title = "CSVUpload";
}

<h2>CSV Bulk Upload</h2>
@using (Html.BeginForm("CSVUpload", "Postings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="file" name="FileUpload" />
    <input type="submit" name="Submit" id="Submit" value="Upload" />

    
   
    @ViewBag.rowcount <p>Postings</p>

    @ViewBag.Feedback;

}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Postings/CreateStart.cshtml
@model CommunityProject_ProjectUnity.Models.Position

@{
    ViewBag.Title = "Create Posting";
}

<h2>Create Posting</h2>
<hr />
<div class="col-lg-10">
<label class="control-label col-md-5">Click To Upload CSV File To Batch Create Postings</label>
@using (Html.BeginForm("CSVUpload", "Postings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    
    <input type="file" name="FileUpload" class="col-lg-offset-6" />
    <br />
    <div class="form-group">
    <label class="control-label col-md-5">OR Select Position as Template</label>
    <input type="submit" name="Submit" id="Submit" value="Upload Postings" class="col-lg-offset-6 btn btn-default" />
    @ViewBag.rowcount
    @ViewBag.Feedback
    </div>
    <br />
    <br />
}
</div>
<br />
@*@Html.ActionLink("Click Me", "CSVUpload", null, new { @class = "btn btn-default col-md-offset-5" })*@




@using (Html.BeginForm("Create", "Postings", FormMethod.Get, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionType, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.DropDownList("PositionType", null, "Select a Position Type", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.JobCode, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.DropDownList("JobTypeID", null, "Select a Job Code", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        @Html.DropDownList("PositionID", null, "Select a Position", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        <input type="text" class="form-control" id="Name" readonly="readonly" />
                    </div>
                </div>
            </div>



            <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionSalary, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        <input type="text" class="form-control" id="Salary" readonly="readonly" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PositionDescription, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        <div class="well" id="Description"></div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Skills, htmlAttributes: new { @class = "control-label col-lg-3 col-md-3 col-sm-8 col-xs-12" })
                    <div class="col-lg-5 col-md-5 col-sm-10 col-xs-12">
                        <div class="well" id="SkillsList"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-3">
                <input type="submit" value="Next Step" class="btn btn-primary col-lg-2" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary col-lg-2 col-md-offset-2" })
            </div>
        </div>
    </div>
}

<div>

</div>
@section Scripts {
    <script type="text/javascript">
          if ($("#PositionType").val() == '0') {
            var jobDefaultValue = "<optipn value='0' >--Select a Job Type--</option>"
            $("#JobTypeID").html(jobDefaultValue).show();
        }
        $("#PositionType").change(function () {
            var selectedItemValue = $(this).val();

            var ddlJobcode = $("#JobTypeID");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetJobCodeByPositionType", "Positions")',
                data: { "ID": selectedItemValue },
                success: function (data) {
                    ddlJobcode.html('');
                    $.each(data, function (id, option) {

                        ddlJobcode.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error.');
                }
            });
        });
        $('#JobTypeID').change(function () {
            var selectedItemValue = $(this).val();

            var ddlPosition = $('#PositionID');
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetPositionByJobCode", "Positions")',
                data: { "ID": selectedItemValue },
                success: function (data) {
                    ddlPosition.html("Select a Position");
                    $.each(data, function (id, option) {
                        ddlPosition.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error.');
                }

            });
            
        });
        $('#PositionID').blur(function () {
            $('#Name').val('');
            $('#Description').empty();
            $('#Salary').val('');
            $('#SkillsList').empty();
            var selectedPosition = $("#PositionID").val();
            var URL = "/Postings/GetAPosition/" + selectedPosition;
            $.getJSON(URL, function (data) {
                if (data != null && !jQuery.isEmptyObject(data)) {
                    $('#Name').val(data.Name);
                    $('#Description').html(data.PositionDescription);
                    $('#Salary').val(data.Salary);
                    $('#SkillsList').html(data.Assignedskill);
                };
            });
        });
    </script>

}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Postings/Index.cshtml
@model PagedList.IPagedList<CommunityProject_ProjectUnity.Models.Posting>
@*@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@
@{
    /**/

    ViewBag.Title = "Posting List";
}
<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <link href="@Url.Content("~/Content/themes/smoothness/jquery-ui-1.7.2.custom.css")" 

              rel="stylesheet" type="text/css" media="all" />
        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" 

              type="text/javascript"></script>
       
        <script src="@Url.Content("~/Scripts/jquery.jeditable.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.js")" 

              type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.dataTables.editable.js")" 

              type="text/javascript"></script>
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>


<script src="//cdn.jsdelivr.net/gh/tuupola/jquery_jeditable@1.7.3/jquery.jeditable.js"></script>
<h2>Job Posting List</h2>
<div>
    @using (Html.BeginForm())
    {
        <p>
            <div class="form-horizontal">
                @*<button class="btn" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
                        Filter/Search Postings
                    </button>
                    <div class="collapse @(ViewBag.Filtering)" id="collapseFilter">*@
                <div class="well">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label col-md-5">Search Position Name: </label>
                                <div class="col-md-7">
                                    @Html.TextBox("searchName", null, new { @class = "form-control" })
                                </div>
                              
                            </div>
                            
                        </div>


                       
                        <div class="form-group">
                            <label class="control-label col-md-offset-o">Filter By FTE: </label>
                            Less than 0.5 @Html.RadioButton("searchFTE", 1)
                            0.5 or more @Html.RadioButton("searchFTE", 2)
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label col-md-5">Filter By Position Status: </label>
                                <div class="col-md-7">
                                    @Html.DropDownList("searchStatus", null, "Select a  Status", htmlAttributes: new { @class = "form-control" })
                                </div>
                                </div>
                            </div>
                         <div class="form-group">
                                 <label class="control-label col-md-offset-o">Filter By Salary Type: </label>
                                 Hourly @Html.RadioButton("SalaryType", 1)
                                 Annually @Html.RadioButton("SalaryType", 2)
                                </div>
                        </div>
                    
                       
                           
                            
                       

                    <div class="row">
                        <div class="col-md-6">
                           
                            <div class="col-md-5"></div>
                            <div class="col-md-8 col-md-offset-7">
                                <input type="submit" name="actionButton" value="Filter" class="btn btn-primary col-lg-4 col-md-offset-2" /> @Html.ActionLink("Clear", "Index", null, new { @class = "btn btn-primary col-lg-4 col-md-offset-2" })
                            </div>
                        </div>
                    </div>
                </div>
                @*</div>*@
            </div>
        </p>
        <p>
            @Html.ActionLink("Create New Posting", "CreateStart", null, new { @class = "btn btn-primary" })
        </p>

        <div class="row">
            
                <div class="panel panel-primary list-panel" id="list-panel">
                    <div class="panel-heading list-panel-heading">
                        <h1 class="panel-title list-panel-title">Postings</h1>
                    </div>
                    <div class="well">
                        <div class="panel-body">
                            <table id="postings-data-table"
                                   class="table table-striped table-bordered"
                                   style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Closing Date</th>
                                        <th>Salary</th>
                                        <th>School</th>
                                        <th>FTE</th>
                                        <th>Openings</th>
                                        <th>Status</th>
                                        <th>Edit Posting</th>
                                        <th>View More Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var posting in Model)
                                    {
                                        <tr>
                                            <td>@posting.Name</td>
                                            <td>@posting.ClosingDate</td>
                                            <td>$@posting.Salary</td>
                                           

                                            <td>
                                                @foreach (var school in posting.Schools)
                                                {
                                                    @school.Shortname<br />
                                                }


                                            </td>
                                            <td>@posting.FTE</td>
                                            <td>@posting.Openings</td>
                                            <td>@posting.status</td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", "Postings", new { id = posting.ID }, null)

                                            </td>
                                            <td>
                                                @Html.ActionLink("Details", "Details", "Postings", new { id = posting.ID }, null)

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
        <span id="filterMessage" class="text-danger">@((Model.Count() == 0) ? "Zero postings found.  No records match your criteria." : "")</span>
        <input type="hidden" name="sortDirection" value="@ViewBag.sortDirection" />
        <input type="hidden" name="sortField" value="@ViewBag.sortField" />
        <br />




        @section Scripts
{
            <script type="text/javascript">
                $(function () {
                    $('#postings-data-table').DataTable({
                        "pageLength": 50,
                       
                        language: {
                            searchPlaceholder: "Type here to Search"
                        }
                    });
                   
                });
            </script>
        }

    }
</div>

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Postings/Save.cshtml
@model CommunityProject_ProjectUnity.Models.Posting

@{
    ViewBag.Title = "Save";
}

<h2>Posting saved to Saved JObs</h2>

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Postings/View.cshtml
@{
    ViewBag.Title = "View";
}

<h2>View</h2>