CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

//testing

namespace CommunityProject_ProjectUnity.Models
{
   
    public class Applicant : Auditable
    {
        public Applicant()
        {
            this.Applications = new HashSet<Application>();
            this.Skills = new HashSet<Skill>();
            this.Files = new HashSet<aFile>();
            this.Qualifications = new HashSet<Qualification>();
            this.Postings = new HashSet<Posting>();
        }

        [Display(Name = "Applicant")]
        public string Summary
        {
            get
            {
                return FormalName + " - email: " + Email;
            }
        }
        public int ID { get; set; }

        [Required(ErrorMessage = "First Name Required")]
        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "First Name Must Be Shorter Than 50 Characters")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        [StringLength(30, ErrorMessage = "Middle name cannot be more than 30 characters long.")]
        public string MiddleName { get; set; }


        [Required(ErrorMessage = "Last Name Required")]
        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "Last Name Must Be Shorter Than 50 Characters")]
        public string LastName { get; set; }

        [Display(Name = "Applicant Name")]
        public string FormalName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        [Display(Name = "Applicant")]
        public string FullName
        {
            get
            {
                return FirstName
                    + (string.IsNullOrEmpty(MiddleName) ? " " :
                        (" " + (char?)MiddleName[0] + ". ").ToUpper())
                    + LastName;
            }
        }
        [Index("IX_Uniqe_Email", IsUnique = true)]
        [Required(ErrorMessage = "Email Address Required")]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        [StringLength(150, ErrorMessage = "Last Name Must Be Shorter Than 150 Characters")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phone Number Required")]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [DisplayFormat(DataFormatString = "{0:(###) ###-####}")]
        [RegularExpression("^\\d{10}$")]
        public string Phone { get; set; }


        //Added to hold picture of applicant
        public virtual ApplicantImage ApplicantImage { get; set; }

        //Added to hold related files
        public ICollection<aFile> Files { get; set; }
        public int QualificationID { get; set; }
      
        public ICollection<Application> Applications { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }

        public virtual ICollection<Posting> Postings { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CommunityProject_ProjectUnity.DAL;
using CommunityProject_ProjectUnity.Models;
using CommunityProject_ProjectUnity.ViewModels;
using PagedList;

namespace CommunityProject_ProjectUnity.Controllers
{
    [Authorize]
    public class ApplicantsController : Controller
    {
        private ProjectUnityEntities db = new ProjectUnityEntities();

        // GET: Applicants
        public ActionResult Index()
        {
            return RedirectToAction("Details");
        }

        // GET: Applicants/Details/5
        public ActionResult Details(int? id)
        {
            Applicant applicant = db.Applicants.Include(p =>p.Files)
                .Include(p =>p.Applications)
                .Include(p =>p.ApplicantImage)
                .Where(c => c.Email == User.Identity.Name).SingleOrDefault();
            //var applicant = db.Applicants.AsNoTracking()
            //    .Include(p => p.Files)
            //    .Include(p => p.Skills)
            //    .Where(p => p.Email == User.Identity.Name);

            if (applicant == null)
            {
                return RedirectToAction("Create");
            }
          
            return View(applicant);
        }

        // GET: Applicants/Create
        public ActionResult Create()
        {
            //Add all (unchecked) Skills to ViewBag
            var applicant = new Applicant();
            applicant.Skills = new List<Skill>();
            PopulateAssignedSkillData(applicant);
            return View();
        }

        // POST: Applicants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,Phone,Email")] Applicant applicant, 
            string[] selectedSkills, IEnumerable<HttpPostedFileBase> Attachments)
        {
            try
            {
                //Add the selected skills
                if (selectedSkills != null)
                {
                    applicant.Skills = new List<Skill>();
                    foreach (var skill in selectedSkills)
                    {
                        var skillToAdd = db.Skills.Find(int.Parse(skill));
                        applicant.Skills.Add(skillToAdd);
                    }
                }
                if (ModelState.IsValid)
                {
                    AddPicture(ref applicant, Request.Files["ProfilePicture"]);
                    AddDocuments(ref applicant, Attachments);
                    db.Applicants.Add(applicant);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DataException dex)
            {
                if (dex.InnerException.InnerException.Message.Contains("IX_Unique"))
                {
                    ModelState.AddModelError("eMail", "Unable to save changes. Remember, no two applicants can have the same eMail address.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again.");
                }
            }

            return View(applicant);
        }

        // GET: Applicants/Edit/5
        public ActionResult Edit(int? id)
        {
            Applicant applicant = db.Applicants.Include(p => p.Files)
                .Include(p => p.Applications)
                .Include(p => p.ApplicantImage)
                .Where(c => c.Email == User.Identity.Name).SingleOrDefault();
            if (applicant == null)
            {
                return RedirectToAction("Create");
            }
           
            PopulateAssignedSkillData(applicant);
            return View(applicant);
        }

        // POST: Applicants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, Byte[] rowVersion, 
            string[] selectedSkills, string chkRemoveImage, IEnumerable<HttpPostedFileBase> Attachments)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicantToUpdate = db.Applicants
                .Include(a => a.Skills).Include(a => a.Files)
                .Include(a => a.ApplicantImage)
               .Where(c => c.Email == User.Identity.Name).SingleOrDefault();
            if (TryUpdateModel(applicantToUpdate, "",
                new string[] { "FirstName", "MiddleName", "LastName", "Phone",}))
            {
                try
                {
                    UpdateApplicantSkills(selectedSkills, applicantToUpdate);
                    if (chkRemoveImage != null)
                    {
                        applicantToUpdate.ApplicantImage = null;
                    }
                    else
                    {
                        AddPicture(ref applicantToUpdate, Request.Files["ProfilePicture"]);
                    }
                    AddDocuments(ref applicantToUpdate, Attachments);
                    db.Entry(applicantToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    db.SaveChanges();
                    return RedirectToAction("Details");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException ex)// Added for concurrency
                {
                    var entry = ex.Entries.Single();
                    var clientValues = (Applicant)entry.Entity;
                    var databaseEntry = entry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError("",
                            "Unable to save changes. The Applicant was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Applicant)databaseEntry.ToObject();
                        if (databaseValues.FirstName != clientValues.FirstName)
                            ModelState.AddModelError("FirstName", "Current value: "
                                + databaseValues.FirstName);
                        if (databaseValues.MiddleName != clientValues.MiddleName)
                            ModelState.AddModelError("MiddleName", "Current value: "
                                + databaseValues.MiddleName);
                        if (databaseValues.LastName != clientValues.LastName)
                            ModelState.AddModelError("LastName", "Current value: "
                                + databaseValues.LastName);
                        if (databaseValues.Phone != clientValues.Phone)
                            ModelState.AddModelError("Phone", "Current value: "
                                + String.Format("{0:(###) ###-####}", databaseValues.Phone));
                      
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                                + "was modified by another user after you received your values. The "
                                + "edit operation was canceled and the current values in the database "
                                + "have been displayed. If you still want to save your version of this record, click "
                                + "the Save button again. Otherwise click the 'Back to List' hyperlink.");
                        applicantToUpdate.RowVersion = databaseValues.RowVersion;
                    }
                }
                catch (DataException dex)
                {
                    if (dex.InnerException.InnerException.Message.Contains("IX_Unique"))
                    {
                        ModelState.AddModelError("EMail", "Unable to save changes. Remember, you cannot have duplicate eMail address.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists go for coffee.");
                    }
                }

            }
            PopulateAssignedSkillData(applicantToUpdate);
            return View(applicantToUpdate);
        }

        // GET: Applicants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // POST: Applicants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applicant applicant = db.Applicants.Find(id);
            try
            {

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applicants/Create.cshtml
@model CommunityProject_ProjectUnity.Models.Applicant

@{
    ViewBag.Title = "Create Applicant";
}

<h2>Create New Applicant</h2>


@using (Html.BeginForm("Create", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <h4>Create  Profile for @User.Identity.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" name="Email" value="@User.Identity.Name" />

    <div class="form-horizontal">

        <hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Profile Picture:</label>
            <div class="col-md-10">
                <input type="file" class="" name="ProfilePicture" /><br />
            </div>
        </div>        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <label class="control-label col-md-2">
                Upload Resumes/Letters:
            </label>
            <div class="col-md-10">
                <input type="file" class="" name="Attachments" multiple="multiple" /><br />
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applicants/Details.cshtml
@model CommunityProject_ProjectUnity.Models.Applicant

@{
    ViewBag.Title = "Profile Details";
}

<h2>Applicant Details</h2>


    <hr />
    <div class="row">
    <div class="col-md-6">
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            <input type="submit" disabled="disabled" value="Uploaded Files" class="btn btn-link" />
        </dt>
        <dd>
            @{
        foreach (var f in Model.Files)
        {
            @:  @Html.ActionLink(f.fileName, "Download", new { id = f.ID }) <br />
}
            }
        </dd>

        </dl>
        </div>
        <div class="col-md-6">
        <dl class="dl-horizontal">


        <dt>
            Applications Submitted
        </dt>

        <dd>
           
            @foreach (var a in Model.Applications)
        {
            @a.Posting.Name <br />
        }
        </dd>
        
    </dl>
</div>
</div>
<p>
    @Html.ActionLink("Edit Profile", "Edit", new { id = Model.ID }) |
  
</p>

CommunityProject-ProjectUnity/CommunityProject-ProjectUnity/Views/Applicants/Edit.cshtml
@model CommunityProject_ProjectUnity.Models.Applicant
@{
    ViewBag.Title = "Edit Applicant";
}

<h2>Edit @Model.FullName</h2>


@using (Html.BeginForm("Edit", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.RowVersion)

        



        <input type="hidden" name="Email" value="@User.Identity.Name" />
        <div class="form-group">
             <div class="col-md-5">
            <label class="control-label col-md-4">Profile Picture:</label>
            
                <input type="file" class="" name="ProfilePicture" /><br />
            </div>
        </div>
        </div>
        <div class="form-group">
            <div class="col-md-5">
                @{
                    if (Model.ApplicantImage != null)
                    {
                        string imageBase64 = Convert.ToBase64String(Model.ApplicantImage.imageContent);
                        string imageSrc = string.Format("data:" + Model.ApplicantImage.imageMimeType + ";base64,{0}", imageBase64);
                        <img src="@imageSrc" style="max-height: 250px; max-width: 300px" class="img-responsive img-rounded" /><br />
                        <input type="checkbox" id="chkRemoveImage" name="chkRemoveImage" /> <strong>Check to remove Picture</strong>
                    }
                }
            </div>
        </div>


        </div>
        <div class="row">
        <div class="horizontal">
        <hr />

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })

                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-4" })

                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })

                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })

                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-5">
                <label class="control-label col-md-4"> Current Documents:</label>

                @foreach (var doc in Model.Files)
                {
                    @doc.fileName <br />
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                <label class="control-label col-md-4">
                    Additional Uploads:
                </label>
                    <input type="file" class="" name="Attachments" multiple="multiple" /><br />
                </div>
            </div>


        <div class="form-group">
            <div class="col-md-12">
            <label class="control-label col-md-2">Aquired Skills</label>
            
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<CommunityProject_ProjectUnity.ViewModels.AssignedSkillVM> skills = ViewBag.Skills;
                            foreach (var skill in skills)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                    name="selectedSkills"
                                    value="@skill.SkillID"
                                    @(Html.Raw(skill.Assigned ? "checked=\"checked\"" : "")) />
                                    @skill.SkillName @:&nbsp;&nbsp;
                                @: </td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>
            <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @Html.ActionLink("Cancel", "Index")
            </div>
        </div>
    </div>
    </div>
}

@*<div>
    @Html.ActionLink("Cancel", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}